# -*- mode: python; -*-
#
# Copyright 2011 Google Inc. All Rights Reserved.
#

package(default_visibility = ['//visibility:private'])

Fileset(
    name = 'src',
    out = 'search',
    entries = [
      FilesetEntry(excludes=[
        'BUILD',
        '.*~',
        ]),
    ])
